### PR TITLE
feedback / suggestions

### PR DESCRIPTION
**Pull request by ianmacartney**
each commit can be individually rejected if you disagree. some big changes are wrapped in single commits, like "prettier" which will make rebasing hard so it'd be nice to not work in parallel rn

----

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ldanilek** [comment]
All looks great, thanks! Do you know why the test is failing?

**Review by ldanilek — APPROVED** [review]

**Comment by ldanilek** [comment]
Oh i missed one of the commits. Why rename public->lib? Do we want to also change other components?

**Comment by ianmacartney** [comment]
> Why rename public->lib? Do we want to also change other components?

Yeah the naming committee came up with a better default than "public" - I've updated some components, we can update more / all

Some other things maybe worth discussing:

- [ ] renaming  completedWorkMaxAgeMs → ttl
- [ ]  there are a lot of knobs, not sure which are actually useful / easy to communicate the value. drop the custom timeoutMs? Or what’s the target usecase here?
- [ ]  Can we use a query subscription on the `ctx.run*` instead of polling in a tight loop?
- [ ]  why is BATCH_SIZE so small?

**Comment by ldanilek** [comment]
> renaming completedWorkMaxAgeMs → ttl

Sgtm


> there are a lot of knobs, not sure which are actually useful / easy to communicate the value. drop the custom timeoutMs? Or what’s the target usecase here?

Yeah i agree. Will have to think about it, but it does feel like too many


> Can we use a query subscription on the ctx.run* instead of polling in a tight loop?

You can't await a query subscription in an action. We could make react hooks in `src/react/`, but i would need to think through the use-case. 

> why is BATCH_SIZE so small?

Ah yeah this is important to reduce OCCs. If you have a steady rate of functions being enqueued and completed, those are mutations pushing onto queues (high creationTimes on the tables) and mainLoop is popping things off queues (low creationTimes on the tables). So to get the most throughput we don't want the mainLoop to completely empty the queues on every iteration, since that will cause an OCC

**Comment by ianmacartney** [comment]
> You can't await a query subscription in an action

It's a bit odd, but could we use the bare ConvexClient w/ subscriptions?

> BATCH_SIZE

how fast can work start/ stop as is? 10 per 50ms? Just curious what the implications here are

**Comment by ldanilek** [comment]
> > You can't await a query subscription in an action
> It's a bit odd, but could we use the bare ConvexClient w/ subscriptions?

Yeah i was in the middle of writing that down when i remembered v8 actions don't implement websockets, just fetch. I suppose you could do a node action but that sounds too heavyweight. 

> > BATCH_SIZE
> how fast can work start/ stop as is? 10 per 50ms? Just curious what the implications here are

we need to do more measurements. I was seeing around 150ms per mainLoop execution which is not as fast as i would like

**Comment by ianmacartney** [comment]
One high level thought is that there's a lot of function calls, bookkeeping & complexity in order to do things like `loop.ctx(ctx).run*` (or I think that's where the complexity comes from).

How confident are you with the ~synchronous API? We can start with a smaller API and add more as necessary, but that one makes me the most nervous b/c of the tight while loop cross-calls.

The scheduler is roughly drop-in, but the IDs will fail to persist in any table where the user uses `v.id("_scheduled_functions")` and I'm not sure whether that's a deal breaker but worth calling out

**Comment by ldanilek** [comment]
> One high level thought is that there's a lot of function calls, bookkeeping & complexity in order to do things like `loop.ctx(ctx).run*` (or I think that's where the complexity comes from).
> 
> How confident are you with the ~synchronous API? We can start with a smaller API and add more as necessary, but that one makes me the most nervous b/c of the tight while loop cross-calls.

i can get rid of the sync calls. reduce it to `pool.scheduler(ctx)`
i'm not sure what complexity you're referring to, but we can remove the loop for sure.

> 
> The scheduler is roughly drop-in, but the IDs will fail to persist in any table where the user uses `v.id("_scheduled_functions")` and I'm not sure whether that's a deal breaker but worth calling out

oh yeah i forgot about schema validation. we should definitely call it out.

**Comment by ianmacartney** [comment]
Yeah up to your comfort level with scalability of different approaches, but
the things that I noticed:

- polling for results
- manually cancelling things after a specified timeout
- ttl for results is only necessary if we track results, vs. forcing them
to persist data into a table
- possible deadlock if the enqueued function has a workpool.run* function
inside it

tbh the API is really slick to be able to do `pool.run*`, I just want to
sanity check that it's not something we'll have to remove / discourage for
bigger customers.

It's too bad that we can't share more logic with the retrier - in some ways
it's a similar problem - run something and keep checking in on it to know
if it transiently failed, and then run a completion handler that usually
happens right away, but if there's transient failure there's a watchdog
that recovers.

**Comment by ldanilek** [comment]
tests are failing so i'll try to land these changes as separate PRs until it fails

**Pull request merged**
